/**
 * Notas del juego de planos de EE.UU. Van en inglés porque las revisa el departamento de construcción.
 * Son notas tipo de vivienda unifamiliar (IRC); el profesional que firma los planos debe ajustarlas a la jurisdicción.
 */

export interface NoteBlock { title: string; notes: string[] }

export const CODES = [
  "2021 INTERNATIONAL RESIDENTIAL CODE (IRC)",
  "2021 INTERNATIONAL ENERGY CONSERVATION CODE (IECC)",
  "2020 NATIONAL ELECTRICAL CODE (NEC / NFPA 70)",
  "2021 INTERNATIONAL PLUMBING CODE (IPC) OR UPC AS ADOPTED",
  "2021 INTERNATIONAL MECHANICAL CODE (IMC)",
  "ALL LOCAL AMENDMENTS AND ORDINANCES OF THE JURISDICTION HAVING AUTHORITY",
];

export const DESIGN_CRITERIA: [string, string][] = [
  ["OCCUPANCY", "R-3 SINGLE FAMILY DWELLING"],
  ["CONSTRUCTION TYPE", "V-B (WOOD FRAME)"],
  ["ROOF LIVE / SNOW LOAD", "20 PSF"],
  ["FLOOR LIVE LOAD", "40 PSF (SLEEPING ROOMS 30 PSF)"],
  ["DEAD LOAD", "ROOF 15 PSF, FLOOR 10 PSF"],
  ["ULTIMATE WIND SPEED", "115 MPH, EXPOSURE B"],
  ["SEISMIC DESIGN CATEGORY", "B (VERIFY WITH JURISDICTION)"],
  ["ALLOWABLE SOIL BEARING", "1,500 PSF (PRESUMPTIVE, IRC R401.4)"],
  ["FROST DEPTH", "PER LOCAL JURISDICTION"],
];

export const GENERAL_NOTES: NoteBlock[] = [
  {
    title: "General",
    notes: [
      "ALL WORK SHALL COMPLY WITH THE CODES LISTED ON SHEET G-001 AND ALL LOCAL ORDINANCES.",
      "CONTRACTOR SHALL VERIFY ALL DIMENSIONS AND CONDITIONS AT THE SITE BEFORE STARTING WORK AND NOTIFY THE DESIGNER OF ANY DISCREPANCY.",
      "DO NOT SCALE DRAWINGS. WRITTEN DIMENSIONS GOVERN. DIMENSIONS ARE TO FACE OF STUD OR FACE OF CONCRETE UNLESS NOTED OTHERWISE.",
      "MEMBER SIZES SHOWN ARE PRELIMINARY PER IRC PRESCRIPTIVE TABLES AND SHALL BE VERIFIED BY A LICENSED DESIGN PROFESSIONAL.",
      "PROVIDE SMOKE ALARMS PER IRC R314 AND CARBON MONOXIDE ALARMS PER IRC R315, HARD-WIRED AND INTERCONNECTED WITH BATTERY BACKUP.",
      "EMERGENCY ESCAPE AND RESCUE OPENINGS IN SLEEPING ROOMS PER IRC R310: 5.7 SQ FT MIN NET CLEAR, 44\" MAX SILL HEIGHT.",
      "SAFETY GLAZING AT HAZARDOUS LOCATIONS PER IRC R308.",
      "PROVIDE FIREBLOCKING AND DRAFTSTOPPING PER IRC R302.11 AND R302.12.",
    ],
  },
  {
    title: "Foundation and concrete",
    notes: [
      "FOOTINGS SHALL BEAR ON UNDISTURBED NATIVE SOIL OR COMPACTED FILL, BELOW FROST DEPTH, 12\" MIN BELOW FINISHED GRADE.",
      "CONCRETE: f'c = 2,500 PSI MIN AT 28 DAYS (3,000 PSI WHERE EXPOSED TO WEATHER) PER IRC R402.2.",
      "REINFORCING STEEL: ASTM A615 GRADE 60. LAP SPLICES 30 BAR DIAMETERS MIN.",
      "SLAB ON GRADE: 4\" CONCRETE OVER 6 MIL VAPOR RETARDER OVER 4\" COMPACTED GRAVEL BASE.",
      "ANCHOR BOLTS: 1/2\" DIA. x 10\" WITH 7\" MIN EMBEDMENT AT 6'-0\" O.C. MAX AND 12\" MAX FROM ENDS OF EACH PLATE (IRC R403.1.6).",
      "SILL PLATES IN CONTACT WITH CONCRETE SHALL BE PRESERVATIVE-TREATED LUMBER.",
    ],
  },
  {
    title: "Wood framing",
    notes: [
      "FRAMING LUMBER: DOUGLAS FIR-LARCH OR SPF #2 OR BETTER, 19% MAX MOISTURE CONTENT, GRADE-STAMPED.",
      "FASTENING PER IRC TABLE R602.3(1) UNLESS NOTED OTHERWISE.",
      "EXTERIOR WALLS: 2x6 STUDS @ 16\" O.C. WITH 7/16\" OSB SHEATHING. INTERIOR WALLS: 2x4 STUDS @ 16\" O.C.",
      "DOUBLE TOP PLATE WITH 48\" MIN LAP AT SPLICES. SINGLE PRESSURE-TREATED BOTTOM PLATE ON CONCRETE.",
      "WALL BRACING PER IRC R602.10 (CONTINUOUSLY SHEATHED WSP METHOD).",
      "ENGINEERED LUMBER (LVL, I-JOISTS, TRUSSES) PER MANUFACTURER; TRUSS DRAWINGS ARE A DEFERRED SUBMITTAL.",
      "PROVIDE SIMPSON (OR EQUAL) HURRICANE TIES AT EACH RAFTER/TRUSS TO TOP PLATE.",
    ],
  },
  {
    title: "Roofing and moisture",
    notes: [
      "ASPHALT SHINGLES CLASS A OVER #15 FELT OR SYNTHETIC UNDERLAYMENT PER IRC R905.2, OVER 7/16\" OSB ROOF SHEATHING.",
      "PROVIDE ICE BARRIER AT EAVES WHERE REQUIRED BY IRC R905.1.2.",
      "ATTIC VENTILATION: 1/150 OF ATTIC AREA (1/300 WITH BALANCED HIGH/LOW VENTS) PER IRC R806.",
      "WEATHER-RESISTIVE BARRIER OVER ALL EXTERIOR SHEATHING. FLASH ALL OPENINGS PER IRC R703.4.",
    ],
  },
  {
    title: "Energy",
    notes: [
      "INSULATION AND FENESTRATION PER IECC TABLE R402.1.3 FOR THE PROJECT CLIMATE ZONE.",
      "TYPICAL MINIMUMS (ZONE 3): CEILING R-30, WOOD FRAME WALL R-20, SLAB EDGE R-10 2 FT, WINDOW U-0.30, SHGC 0.25.",
      "AIR LEAKAGE TEST: 5 ACH50 MAX PER IECC R402.4.1.2. DUCT LEAKAGE TEST PER R403.3.",
      "PROVIDE A PERMANENT ENERGY CERTIFICATE AT THE ELECTRICAL PANEL PER IECC R401.3.",
    ],
  },
];

export const ABBREVIATIONS: [string, string][] = [
  ["A.B.", "ANCHOR BOLT"], ["A.F.F.", "ABOVE FINISHED FLOOR"], ["CONC.", "CONCRETE"], ["CLG.", "CEILING"],
  ["DBL.", "DOUBLE"], ["DIA.", "DIAMETER"], ["EA.", "EACH"], ["EXT.", "EXTERIOR"], ["FTG.", "FOOTING"],
  ["GFCI", "GROUND-FAULT CIRCUIT INTERRUPTER"], ["AFCI", "ARC-FAULT CIRCUIT INTERRUPTER"], ["HDR.", "HEADER"],
  ["INT.", "INTERIOR"], ["LVL", "LAMINATED VENEER LUMBER"], ["MAX.", "MAXIMUM"], ["MIN.", "MINIMUM"],
  ["O.C.", "ON CENTER"], ["OSB", "ORIENTED STRAND BOARD"], ["P.T.", "PRESSURE TREATED"], ["TYP.", "TYPICAL"],
  ["U.N.O.", "UNLESS NOTED OTHERWISE"], ["V.I.F.", "VERIFY IN FIELD"], ["W.S.P.", "WOOD STRUCTURAL PANEL"],
];

export const SCOPE = "NEW SINGLE FAMILY RESIDENCE, WOOD FRAME CONSTRUCTION ON CONCRETE SLAB-ON-GRADE FOUNDATION, WITH ASSOCIATED SITE, ELECTRICAL, PLUMBING AND MECHANICAL WORK.";

export const DEFERRED = ["PREFABRICATED ROOF TRUSSES (IF USED)", "FIRE SPRINKLERS (IF REQUIRED BY JURISDICTION)", "SOLAR PHOTOVOLTAIC SYSTEM (IF ANY)"];

/** Notas de cada lámina, por tipo de contenido. */
export const SHEET_NOTES: Record<string, string[]> = {
  site: [
    "LOT LINES AND SETBACKS ARE SHOWN FOR REFERENCE ONLY. VERIFY WITH A BOUNDARY SURVEY BY A LICENSED SURVEYOR.",
    "SETBACKS SHOWN: FRONT 25'-0\", REAR 20'-0\", SIDES 5'-0\". VERIFY WITH LOCAL ZONING.",
    "SLOPE FINISHED GRADE AWAY FROM FOUNDATION 6\" MIN IN THE FIRST 10'-0\" (IRC R401.3).",
    "LOCATE ALL UNDERGROUND UTILITIES BEFORE EXCAVATION (CALL 811).",
    "DOWNSPOUTS SHALL DISCHARGE TO SPLASH BLOCKS OR APPROVED DRAINAGE, 5'-0\" MIN FROM FOUNDATION.",
    "PROVIDE EROSION AND SEDIMENT CONTROL DURING CONSTRUCTION AS REQUIRED.",
  ],
  found: [
    "SEE GENERAL NOTES ON G-002 FOR CONCRETE AND REINFORCING.",
    "F1: 16\" WIDE x 8\" DEEP CONTINUOUS FOOTING WITH (2) #4 BARS CONT. AT EXTERIOR WALLS.",
    "F2: 12\" WIDE x 8\" DEEP THICKENED SLAB WITH (1) #4 BAR CONT. AT INTERIOR BEARING WALLS.",
    "BOTTOM OF FOOTING 12\" MIN BELOW GRADE OR BELOW FROST DEPTH, WHICHEVER IS DEEPER.",
    "4\" CONCRETE SLAB OVER 6 MIL VAPOR RETARDER OVER 4\" GRAVEL. SAW-CUT CONTROL JOINTS AT 12'-0\" O.C. MAX.",
    "1/2\" DIA. ANCHOR BOLTS @ 6'-0\" O.C. MAX, 12\" MAX FROM PLATE ENDS, 2 MIN PER PLATE SECTION.",
    "SLAB EDGE INSULATION PER ENERGY NOTES.",
  ],
  floorfr: [
    "JOIST SIZES PER IRC TABLE R502.3.1(2) (FLOORS) OR R802.4.1(1) (CEILINGS), DF-L / SPF #2.",
    "JOISTS SHALL BEAR 1-1/2\" MIN ON WOOD OR 3\" ON MASONRY/CONCRETE.",
    "PROVIDE SOLID BLOCKING AT BEARING POINTS AND BRIDGING AT 8'-0\" O.C. MAX FOR JOISTS 2x12 AND DEEPER.",
    "DOUBLE JOISTS UNDER PARALLEL BEARING PARTITIONS.",
    "FLOOR SHEATHING: 23/32\" T&G OSB, GLUED AND NAILED. CEILING: 1/2\" GYPSUM BOARD.",
    "NOTCHES AND HOLES PER IRC R502.8.",
  ],
  wallfr: [
    "EXTERIOR WALLS: 2x6 STUDS @ 16\" O.C. INTERIOR WALLS: 2x4 STUDS @ 16\" O.C. U.N.O.",
    "HEADERS PER SCHEDULE, (1) JACK AND (1) KING STUD EACH SIDE MIN, PER IRC R602.7.",
    "EXTERIOR SHEATHING 7/16\" OSB WITH 8d NAILS @ 6\" O.C. EDGES / 12\" O.C. FIELD.",
    "BRACED WALL PANELS PER IRC R602.10, CONTINUOUSLY SHEATHED (CS-WSP).",
    "DOUBLE TOP PLATE, LAP 48\" MIN. P.T. BOTTOM PLATE AT SLAB.",
    "FIREBLOCK AT CEILING AND FLOOR LEVELS AND AT 10'-0\" MAX VERTICALLY.",
  ],
  rooffr: [
    "RAFTER SIZES PER IRC TABLE R802.5.1, 20 PSF SNOW / LIVE LOAD, DF-L / SPF #2, @ 24\" O.C.",
    "RIDGE BOARD 2\" NOMINAL DEPTH NOT LESS THAN CUT END OF RAFTER (IRC R802.3).",
    "CEILING JOISTS OR RAFTER TIES TO RESIST THRUST, IN LOWER THIRD OF ATTIC SPACE (IRC R802.5.2).",
    "HURRICANE TIES AT EACH RAFTER TO TOP PLATE.",
    "ROOF SHEATHING 7/16\" OSB WITH H-CLIPS; 8d NAILS @ 6\" O.C. EDGES / 12\" O.C. FIELD.",
    "IF PREFABRICATED TRUSSES ARE USED, TRUSS DESIGN DRAWINGS ARE A DEFERRED SUBMITTAL.",
  ],
  plan: [
    "DIMENSIONS ARE TO FACE OF STUD OR CENTER OF WALL U.N.O.",
    "SEE SCHEDULES FOR DOOR AND WINDOW SIZES. VERIFY ROUGH OPENINGS WITH MANUFACTURER.",
    "SLEEPING ROOM WINDOWS SHALL MEET EGRESS REQUIREMENTS (IRC R310).",
    "SMOKE ALARMS IN EACH SLEEPING ROOM, OUTSIDE EACH SLEEPING AREA AND ON EACH STORY.",
    "1/2\" GYPSUM BOARD ON ALL INTERIOR WALLS AND CEILINGS; WATER-RESISTANT BOARD AT WET AREAS.",
    "PROVIDE R-30 MIN ATTIC INSULATION AND R-20 MIN EXTERIOR WALL INSULATION.",
  ],
  elev: [
    "FINISHED GRADE SHOWN IS APPROXIMATE. SLOPE AWAY FROM FOUNDATION.",
    "PROVIDE 6\" MIN CLEARANCE FROM WOOD SIDING TO FINISHED GRADE (IRC R317.1).",
    "FLASH ALL WINDOW AND DOOR HEADS, SILLS AND JAMBS.",
    "ROOF: ASPHALT SHINGLES CLASS A. GUTTERS AND DOWNSPOUTS AS SHOWN.",
    "MAXIMUM BUILDING HEIGHT PER LOCAL ZONING.",
  ],
  sec: [
    "SEE G-002 FOR FRAMING, INSULATION AND ROOFING NOTES.",
    "CEILING HEIGHTS ARE TO FINISHED CEILING.",
    "ATTIC ACCESS 22\" x 30\" MIN PER IRC R807.",
    "VERIFY ALL STRUCTURAL MEMBERS WITH FRAMING PLANS S-101 TO S-104.",
  ],
  details: [
    "DETAILS ARE TYPICAL AND APPLY WHEREVER SIMILAR CONDITIONS OCCUR.",
    "SEE GENERAL NOTES FOR MATERIAL SPECIFICATIONS.",
  ],
  details2: [
    "DETAILS ARE TYPICAL AND APPLY WHEREVER SIMILAR CONDITIONS OCCUR. USE THE FOUNDATION TYPE SHOWN ON S-101.",
    "CONCRETE f'c = 2,500 PSI MIN (3,000 PSI WHERE EXPOSED TO WEATHER). REBAR ASTM A615 GRADE 60, 3\" MIN COVER AGAINST EARTH.",
    "CMU ASTM C90, TYPE S MORTAR, GROUT f'c = 2,000 PSI MIN. GROUT ALL CELLS WITH REBAR OR ANCHOR BOLTS.",
    "FOOTINGS BEAR ON UNDISTURBED SOIL OR COMPACTED FILL, 1,500 PSF PRESUMPTIVE (IRC TABLE R401.4.1).",
    "CRAWL SPACE ACCESS 18\" x 24\" MIN (IRC R408.4). NO WOOD WITHIN 18\" OF GROUND UNLESS P.T.",
    "PROVIDE TERMITE PROTECTION PER IRC R318 WHERE REQUIRED.",
  ],
  details3: [
    "DETAILS ARE TYPICAL AND APPLY WHEREVER SIMILAR CONDITIONS OCCUR.",
    "STAIRS PER IRC R311.7; GUARDS PER R312, 36\" MIN, OPENINGS LESS THAN 4\" SPHERE.",
    "WINDOWS INSTALLED PER MANUFACTURER AND ASTM E2112. FLASHING PER IRC R703.4.",
    "DECKS PER IRC R507. ALL FASTENERS AND CONNECTORS IN P.T. LUMBER HOT-DIP GALVANIZED OR STAINLESS.",
    "SAFETY GLAZING WHERE REQUIRED BY IRC R308.4.",
  ],
  elec: [
    "ALL ELECTRICAL WORK PER NEC 2020 AND LOCAL AMENDMENTS.",
    "200A, 120/240V, 1-PHASE MAIN SERVICE PANEL U.N.O. GROUNDING ELECTRODE SYSTEM PER NEC 250.",
    "AFCI PROTECTION FOR ALL 120V 15/20A BRANCH CIRCUITS IN DWELLING ROOMS (NEC 210.12).",
    "GFCI PROTECTION AT BATHROOMS, KITCHEN COUNTERS, GARAGE, OUTDOORS AND LAUNDRY (NEC 210.8).",
    "RECEPTACLES TAMPER-RESISTANT. SPACING SO NO POINT ALONG WALL IS MORE THAN 6'-0\" FROM AN OUTLET.",
    "(2) 20A SMALL APPLIANCE CIRCUITS AT KITCHEN, 20A LAUNDRY AND 20A BATHROOM CIRCUITS.",
    "SMOKE AND CO ALARMS HARD-WIRED AND INTERCONNECTED.",
    "100% HIGH-EFFICACY LIGHTING PER IECC R404.1.",
  ],
  plum: [
    "ALL PLUMBING WORK PER IPC/UPC AS ADOPTED BY THE JURISDICTION.",
    "WATER SUPPLY: PEX OR TYPE L COPPER. DRAINAGE AND VENT: PVC OR ABS SCHEDULE 40.",
    "PROVIDE MAIN SHUTOFF VALVE AND PRESSURE REDUCING VALVE IF PRESSURE EXCEEDS 80 PSI.",
    "WATER HEATER WITH T&P RELIEF VALVE PIPED TO AN APPROVED LOCATION; SEISMIC STRAPS WHERE REQUIRED.",
    "SHOWER VALVES PRESSURE-BALANCED OR THERMOSTATIC, 120°F MAX.",
    "SLOPE DRAIN PIPING 1/4\" PER FOOT MIN (1/8\" FOR 3\" AND LARGER).",
    "PROVIDE CLEANOUTS AT EACH CHANGE OF DIRECTION GREATER THAN 45° AND AT BASE OF STACKS.",
  ],
  hvac: [
    "ALL MECHANICAL WORK PER IMC / IRC CHAPTERS 13-24.",
    "EQUIPMENT SIZED PER ACCA MANUAL J / S; DUCTS PER MANUAL D. SIZES SHOWN ARE PRELIMINARY.",
    "SUPPLY DUCTS: INSULATED FLEX OR SHEET METAL, R-8 IN UNCONDITIONED ATTIC. SEAL ALL JOINTS WITH MASTIC.",
    "BATHROOM EXHAUST FANS 50 CFM MIN INTERMITTENT, DUCTED TO EXTERIOR (IRC M1505).",
    "KITCHEN HOOD 100 CFM MIN, DUCTED TO EXTERIOR.",
    "CONDENSATE DRAIN TO APPROVED LOCATION WITH SECONDARY PAN OR FLOAT SWITCH.",
    "WHOLE-HOUSE MECHANICAL VENTILATION PER IRC M1505.4.",
    "OUTDOOR UNIT ON 4\" CONCRETE PAD, 3'-0\" MIN CLEARANCE FROM OPENINGS.",
  ],
};
